### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by Hello-Pig** [Bklieger/groqnotes#14]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://groqnotes.streamlit.app/bklieger/groqnotes/deploy/main.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by Bklieger** [comment]
The YouTube download feature has recently caused issues with Streamlit hosted resource limits. This is likely related to https://github.com/Bklieger/groqnotes/issues/4.

You can use the Replit hosted version instead:
https://groqnotes.replit.app
