### ISSUE TITLE
Hallucination

### ISSUE THREAD

**Issue by gentonje** [Bklieger/groqnotes#21]
While the pdf generation is excellent and fast, i realized some minor error, the book was about crop diseases, and somewhere in the middle the books switched to human diseases for a few pages then back to animal diseases,is it a possible issue with the model or maybe my prompt was not clear enough

**Comment by Bklieger** [comment]
You can try switching the model to experiment. Based on what you described, it sounds like the outline generated included an irrelevant section about human and animal diseases. Therefore, try swapping the outline generation model under the custom settings on the left sidebar.  Additionally as you mentioned, you can provide more precise content for the models, which will also improve output.
